### ISSUE TITLE
The need for more datasets

### ISSUE THREAD

**Issue by Li-Tian-Le** [ZackZikaiXiao/FedGraB#5]
I am reproducing your experimental results, but there is only cifar10 in the code at present. Could you please make the implementation code of cifar100, imagenet and other datasets public?

**Comment by ZackZikaiXiao** [comment]
The latest [FedLoGe repository](https://github.com/ZackZikaiXiao/FedLoGe) contains the code for constructing datasets for different settings, including heterogeneity and long-tail. Below are the links to the datasets and the corresponding code: [CIFAR-100 Dataset Code](https://github.com/ZackZikaiXiao/FedLoGe/blob/master/util/dataset.py), [ImageNet Dataset](https://drive.google.com/file/d/1u5XF0AsDm0GRoEp3HJPZ_sSvvWb4BVCv/view?usp=drive_link), [iNaturalist 2018 Dataset](https://drive.google.com/file/d/1HLqF_n1Z8VUCIV3jDHhLmQXFrqs3CacR/view?usp=drive_link).

**Comment by tiantianbjut** [comment]
> I am reproducing your experimental results, but there is only cifar10 in the code at present. Could you please make the implementation code of cifar100, imagenet and other datasets public?

Could you please let me know if you were able to successfully reproduce it?

**Comment by Li-Tian-Le** [comment]
Thank you for your response. I am currently conducting experiments under a different long-tail scenario (where each client has an equal amount of data). Since FedGrab only discusses the 10-class scenario in the current implementation, I have not been able to reproduce the results of FedGrab on the CIFAR-100, ImageNet, or iNaturalist 2018 datasets. Could you please provide further clarification or guidance on these settings? It would be helpful to understand how to adapt the code for these datasets or the specific modifications required for scenarios beyond the 10-class case.

**Comment by tiantianbjut** [comment]
> clarification or guidance on these settings? It would be helpful to understand how to adapt the code for these datasets or the

I apologize for not having a solution at the moment, but I'm encountering some challenges while trying to reproduce the CIFAR-10 dataset. If possible, could you kindly share your email address so we could discuss this further? Thank you very much!
